version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: telegram-db
    restart: always
    environment:
      POSTGRES_USER: bot
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: botdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  telegram-bot:
    image: atsinin/time-keeper-tg-bot:latest
    container_name: telegram-bot-pg
    restart: always
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DATABASE_URL=postgres://bot:secret@postgres:5432/botdb?sslmode=disable
    depends_on:
      - postgres

volumes:
  postgres_data:
